SELECT * FROM MEMBERTBL;

INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('ONETWO', '하나둘', '하나둘시셋넷다섯');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('ONETWO', '하나셋둘', '하나둘시셋넷다섯');

CREATE TABLE "SHOP"."PRODUCTTBL"
(PRODUCTNAME NCHAR(20) NOT NULL,
COST NUMBER(8) NOT NULL,
MAKEDATE DATE,
COMPANY NCHAR(8),
AMOUNT NUMBER(5),
CONSTRAINT PRODUCTNAME_PK PRIMARY KEY
    (PRODUCTNAME)ENABLE);

INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES ('갤럭시아머니트리', '14000', '2021-12-25', 'NFT', '1850');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES ('덱스터', '35000', '2021-12-28', 'METABUS', '400');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES ('DSC INVESTMENT2', '7000', '2021-06-25', 'INVESTMENT', '6000');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES ('스텔라루멘', '250', '2020-02-21', 'RUMEN COIN', '400');

SELECT * FROM PRODUCTTBL;
SELECT COMPANY FROM PRODUCTTBL;

SHOW TABLES;

CREATE TABLE FFJUIV
(FDSF CHAR(20) NOT NULL,
GRIJG CHAR(20),
RUGHRG CHAR(20),
GREG CHAR(20)); -- CREATE 테이블
ALTER TABLE FFJUIV MODIFY FDSF VARCHAR(30); -- 데이터 형식 변경
INSERT INTO FFJUIV VALUES ('FF', 'FFA', 'FGG' , 'GFG');
INSERT INTO FFJUIV VALUES ('FF', 'FFA', 'FGG' , 'GFG33');
SELECT * FROM FFJUIV;

ALTER TABLE FFJUIV ADD ADDCOLUMN NCHAR(20); -- 컬럼 ADD하기

INSERT INTO FFJUIV VALUES ADDCOLUMN = 'ADDED';
UPDATE FFJUIV SET ADDCOLUMN = 'ADDED' WHERE GREG = 'GFG33'; 
